---
# tasks file for root_credentials
#
  - name: Ensure admin account exists in files
    user:
      name: admin
      password: "{{ admin_password }}"
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
      local: yes
      state: present
      force: no

  - name: Ensure admin pubkey is present
    authorized_key:
      user: admin
      state: present
      key: "{{ admin_ssh_key }}"

  - name: Ensure sudoers.d for admin exists
    copy:
      src: admin
      dest: "/etc/sudoers.d/admin"
      owner: root
      group: root
      mode: "0440"
      validate: 'visudo -c'
    

    notify:
      restart ssh

